In [23]:
from sklearn.cluster import SpectralClustering
import numpy as np

## Create a symmetric adjacency matrix

In [27]:
N = 40
adj_matrix = np.random.choice([0,1],p=[.8, .2],size=(N,N))
lower_triag_adj_matrix = adj_matrix - np.triu(adj_matrix)
upper_triag_adj_matrix = np.rot90(np.fliplr(lower_triag_adj_matrix))

adj_matrix = lower_triag_adj_matrix + upper_triag_adj_matrix
adj_matrix

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

## Cluster the values of the matrix

In [48]:
n_clusters = 15
row_cluster_labels = SpectralClustering(n_clusters=n_clusters, random_state=42, assign_labels="discretize").fit(adj_matrix).labels_
row_cluster_labels

array([ 2,  2,  4,  1, 12,  9, 13,  8,  4,  4, 12, 12,  6,  5, 14,  1,  1,
       14,  7, 10,  3,  2, 11,  5,  2,  6,  3,  1,  8, 13,  9,  7,  1,  2,
        7,  2, 10,  4, 11, 12])

## Get new order of rows and columns

In [49]:
new_order = np.argsort(row_cluster_labels)
new_order


array([ 3, 32, 16, 15, 27,  0, 24, 21, 35, 33,  1, 26, 20,  8, 37,  2,  9,
       13, 23, 12, 25, 31, 34, 18,  7, 28, 30,  5, 36, 19, 22, 38, 11, 10,
        4, 39,  6, 29, 17, 14])

## Perform the reordering

In [50]:
clustered_adj_matrix = adj_matrix[new_order][:, new_order]
clustered_adj_matrix

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

## Save the matrix as a CSV file

In [51]:
np.savetxt("clustered_adj_matrix.csv", clustered_adj_matrix, delimiter=",", fmt="%i")